sudo: required
dist: jammy
addons:
  chrome: stable
  firefox: latest
language: node_js
services:
- xvfb
node_js:
- lts/*
cache:
- node_modules
install:
- yarn install
script:
- yarn run test --coverage
  yarn run test --browsers=Firefox
- if [[ $TRAVIS_TEST_RESULT -eq 0 ]]; then cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js; fi
