sudo: required
dist: jammy
addons:
  chrome: stable
  firefox: latest
language: node_js
services:
- xvfb
node_js:
- lts/*
cache:
- node_modules
before_install:
- export START_TIME=$( date +%s )
- npm i -g yarn
install:
- yarn install
script:
- yarn run test --coverage
  yarn run test --browsers=Firefox
- if [[ $TRAVIS_TEST_RESULT -eq 0 ]]; then cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js; fi
after_script:
- export END_TIME=$( date +%s )
- ckeditor5-dev-ci-notify-travis-status
