sudo: required
dist: trusty
addons:
  chrome: stable
  firefox: latest
language: node_js
node_js:
- '8'
cache:
- node_modules
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- yarn install
script:
- yarn run test --coverage && yarn run test --browsers=Firefox,BrowserStack_Edge,BrowserStack_Safari
env:
  global:
  - secure: cUYeLfFNWafic3oZRy7ai2Ok08BeRIUsZvSyyUq8KBAJ2SyhjzDawWzxuGvqGjg6UsU73pao11q9rr2jA2m6bEcxx3XeO/TnSVTW/bIiEmDgsubcVG6vjNzissJBLJBd+UqXHbb8tFjUvmlKsk7bAeM19sh4GOQQ0VxuphZLGrOqXSb+w1hW0pjiA8nBTUoTt0LgDLH0cLaKH0XI7/E5TxEo4ne4Gr+ibd0jZiE/vkHhZ/S84u+zedsbNDP7pNgjhW/EvNePdkB1gGlJir92C33J0GYXGfjiAwhLYkrqIc07gHpCPevcxEvVJbT5B6w4ELUdLy6fbjB0ZC3cJkxTLXnmCUCwL2keqwmc/arwmIguLfjJCMKuZIssivA7fwKJMuOtJV6U8CzJsNHVAG35pfoR5jyt4DIjUNr2AgW72krIkEKCD/r1lxGlkIYY864ZHkfbqLa/YTgR6FRPCeoYC8WDbf+k1tA/X3bmGEYEWzChkuFkWdCQUi/LgSbDaEQ1BH36WKp0APXKoPoDCAZQqjfkgu8NkGcvnM84Ll4QJIw4vwbZSAJJGEQSS63gNsC4xglyqqLVq0w/uFhekQT2iHaLRocgsMPvYCldAuSA8zsPUHaiUb24BNllTVoHAXvAzdzSmrkllqI3Ew0K1butZP9S8sJnumfUCs9NUVuW3+A=
  - secure: lmMFP7ICdjof81wpx5flPdS+m+5CtKNG86fikvOvcMfo6FhiIy87KeNViyWvzJ/4zpf/i9hl+JjOnERG1TN4pK0J/jhtr/SfTKS3FKjexhSdW4eASE1gqCSC4S0nSNJ11kmU19FRb82kcM1G+BlqVSikBfFq0JFSQMjq4yrEAcpKhzmRmTa/wWzqEadNkT+m8c8qanNWbUDyKy7z+3iSvq5fU23tckwovs+jQ/AYjG/wg1ojNG7KLnOBoV5J4lSwrdXE4ttsFZrvZ9WDN09XMs5tAqJYSGDg1RgGHPJqyh6UYBRV7589v+/gr+cTFJU6pXTatk/vwI3f4OjBfYDBzTjZ7pFr9oNbPLYQGWu8vYvqlwy5b8tQzYiQ95PYKGIa06T92QttN4uWRI8+OtLwv/OdmZxwjwTLWB0Tr04MMzbmFVUB/urqy3t/mgZlKE03JbIJGyzT5uk4pjf6RXjpF3b3Njay+e2X4Xcxnml8cRgxR19lIMdaoexli72QX2KmIghvT2m5NvsCydRSeUFDqHAMXYUG5pC8BAt5/wphsJfNk3Uds5cedZh0/oorYV3ea/LtTaTbJ6WtQgUvA6BUpL18TVkQj4zPihstbFmEXaMEvBML6PiftXXu/g22qrhzBnSiW8uAfJmvF+A+mfdAQ7jo9V6CoXAZi/wvZBzE8mA=
