sudo: required
dist: xenial
addons:
  chrome: stable
  firefox: latest
language: node_js
services:
- xvfb
node_js:
- '8'
cache:
- node_modules
install:
- yarn install
script:
- yarn run test --coverage && yarn run test --browsers=Firefox
