onlyBuiltDependencies:
  - esbuild

overrides:
  'nth-check@<2.0.1': ^2.1.1
  'qs@^6.0.0': '^6.14.1'
  tar@^6.0.0: ^7.5.4
  diff@<4.0.4: ^4.0.4
  diff@^7.0.0: ^8.0.3

minimumReleaseAge: 4320 # 3 days
minimumReleaseAgeExclude:
  - '@ckeditor/*'
  - '@cksource/*'
  - '*ckeditor5*'

shellEmulator: true
shamefullyHoist: true
preferFrozenLockfile: true
