allowBuilds:
  esbuild: true
  snyk: true

minimumReleaseAge: 4320 # 3 days
minimumReleaseAgeExclude:
  - '@ckeditor/*'
  - '@cksource/*'
  - '*ckeditor5*'

shellEmulator: true
shamefullyHoist: true
preferFrozenLockfile: true
verifyDepsBeforeRun: false
